services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/backend
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    command: su -c "python manage.py migrate && gunicorn backend.wsgi:application --bind 0.0.0.0:8000"
    env_file:
      - ./.env
  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000
  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_DB: ToDoOverEngineered
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: pg
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  nginx:
    build: .
    ports:
      - 80:80  # Map container port 80 to host port 80
    depends_on:
      - backend
      - frontend
    