services:
  backend_user:
    build:
      context: ./User
    volumes:
      - ./User:/User
    ports:
      - 8000:8000
    depends_on:
      dbUser:
        condition: service_healthy
    command: su -c "python manage.py migrate && gunicorn backend.wsgi:application --bind 0.0.0.0:8000"
    env_file:
      - ./.env
  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000
  dbUser:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_DB: dbUser
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: pg
    volumes:
      - ./postgres_data_user:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  nginx:
    build: .
    ports:
      - 80:80  # Map container port 80 to host port 80
    depends_on:
      - backend_user
      - frontend
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      
volumes:
  rabbitmq_data:
